name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('todoapp-swe451/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: List Files (debugging)
        run: ls -R

      - name: Compile Project
        run: mvn compile
        working-directory: ./todoapp-swe451

      - name: Run Unit Tests
        run: mvn test
        working-directory: ./todoapp-swe451

      - name: Build with Maven (skip repackage issues)
        run: mvn clean package -DskipTests -Dspring-boot.repackage.skip=true
        working-directory: ./todoapp-swe451

